### ISSUE TITLE
logo-design needed

### ISSUE THREAD

**Issue by hueitan** [hueitan/javascript-sdk-design#1]

**Comment by huei90** [comment]
# Javascript SDK / @ Javascript SDK / ! Javascript SDK
# JavaScript SDK / @ JavaScript SDK / ! JavaScript SDK
# javascript sdk / @ javascript sdk / ! javascript sdk
# javascript SDK / @ javascript SDK / ! javascript SDK
# JAVASCRIPT SDK / @ JAVASCRIPT SDK / ! JAVASCRIPT SDK
# JAVASCRIPT sdk / @ JAVASCRIPT sdk / ! JAVASCRIPT sdk

**Comment by natos** [comment]
Here's a little concept to start

![js sdk logo](https://cloud.githubusercontent.com/assets/242562/21261240/6f7834ee-c38a-11e6-8283-dce5a8c053af.png)

**Comment by huei90** [comment]
@natos thank you thank you very much for your comment 😭  finally there is someone here.

I like the concept that using the box, i like it.

but the box colour can be discussed.

**Comment by hueitan** [comment]
I will close this as I don't really need this, to be honest ;-)
