### ISSUE TITLE
CORS  https to http

### ISSUE THREAD

**Issue by wangduanduan** [hueitan/javascript-sdk-design#12]
I make a JavaScript SDK, in customer's dev environment and test environment, it does not have any problem.  but  when project on the line, a big problem came suddenly。

in production environment, customer use https protocol, but my sdk use http protocol。

browser will refuse a send a xhr request from htttps to http. so i want to remind others peopel.

**Comment by hueitan** [comment]
yes, this is expected. you should better support https as well.

**Comment by hueitan** [comment]
If your SDK js supports both `http` `https`, then you can include your SDK 

```js
s.src = '//xxx.com/sdk.js'
```
the browser will detect the page and give you either http or https
