### ISSUE TITLE
Ask SDKName undefined

### ISSUE THREAD

**Issue by appzone** [hueitan/javascript-sdk-design#13]
Hi, 

i try the example code in here

i try to load code Async, but i got the SDKName undefined

 // add a queue event here
    SDKName = SDKName || function () {
      (SDKName.q = SDKName.q || []).push(arguments);
    };

i change SDKName to my own SDK name

if i load it sync, the things ok.

can help?

thanks

**Comment by hueitan** [comment]
> The event will store in the SDKName.q queue array, your SDK should handle and execute SDKName.q and reinitiate the namespace SDKName

Hope this is useful to you 🚀

**Comment by cristianDroguett** [comment]
Hi @hueitan i have the same problem as @appzone I understand about SDKName.q but I did't make it, can you give us an example code?, please. I have this code
`(function () {
			FI = FI || function () {
				(FI.q = FI.q || []).push(arguments);
			};
			var s = document.createElement('script');
			s.type = 'text/javascript';
			s.async = true;
			s.src = 'http://localhost/SimpleFiSDK/api/js/bundle.js';
			(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(s);
		})();
		FI.load('9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b', {
			data: {
				plazo: 120,
				monto: 12000000,
			}
		});`

**Comment by hueitan** [comment]
@cristianDroguett by the code you given here, `FI.load` is `undefined` because your script hasn't loaded yet. you should use

```js
FI('9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b', {
    data: {
      plazo: 120,
      monto: 12000000,
}
```

then within your `bundle.js` code, remember to check the queue `FI.q` and execute them.

hope this is clear to you.

**Comment by hueitan** [comment]
reopen the issue if you need further help.
