### ISSUE TITLE
  s.src = 'http://xxx.com/sdk.js'; Is a valid domain, please change it

### ISSUE THREAD

**Issue by adamellsworth** [hueitan/javascript-sdk-design#15]
I forgot to change the URL when I copied one of the examples and mistakenly made valid requests to `xxx.com/sdk.js` over my company's network.

To prevent others from making the same mistake and potentially getting fired or reprimanded, it would be wise to change it to something like `https://<YOUR DOMAIN>.com/sdk.js`

**Comment by hueitan** [comment]
:+1: Thanks! Your suggestion is valid and true, let's change to the URL you suggest! Do you mind sending pull request to update it?

**Comment by adamellsworth** [comment]
https://github.com/hueitan/javascript-sdk-design/pull/16
