### ISSUE TITLE
The example of check-third-party-cookie-writable is broken

### ISSUE THREAD

**Issue by ysde** [hueitan/javascript-sdk-design#20]
Hi @hueitan 

The link of the example of [check-third-party-cookie-writable](https://github.com/hueitan/javascript-sdk-design#check-third-party-cookie-writable) is broken.

Can you help fix it?

Thank you

**Comment by hueitan** [comment]
I'm open for anyone to submit a pr for this :tada:

**Comment by hueitan** [comment]
I have removed the link, if anyone finds a readable link, do share and I can update it :link:
