### ISSUE TITLE
Building a Web SDK (Inprogress)

### ISSUE THREAD

**Issue by hueitan** [hueitan/javascript-sdk-design#3]
# TOC
- [Target Audience](#issuecomment-159792296)
- [Good to know](#issuecomment-159792475)
- [Where to Use](#issuecomment-159792518)
- [Scope of SDK](#issuecomment-159792536)
- [Philosophy](#issuecomment-159792550)
- [Include/Import Scripts in Browser](#issuecomment-159792586)
- [Namespace Collision](#issuecomment-159792598)
- [Interface API](#issuecomment-159792608)
- _Storage Mechanism_ (to be added)
- _Request_ (to be added)
- _more to be added_
- [Q&A](#issuecomment-159792616)

**Comment by huei90** [comment]
### Target Audience

* Nothing to Web - Good to start
* Basic/New to Web - This is a little bit detail
* Back End Engineer - This has nothing to do with you
* Front End Engineer - You might already know it
* Full Stack Engineer - You are already Expert

**Comment by huei90** [comment]
Good to Know
===

**Comment by huei90** [comment]
Where to Use
===

**Comment by huei90** [comment]
Scope of SDK
===

**Comment by huei90** [comment]
Philosophy
===

**Comment by huei90** [comment]
Include/Import Scripts in Browser
===

**Comment by huei90** [comment]
Namespace Collision
===

**Comment by huei90** [comment]
Interface API
===

**Comment by huei90** [comment]
Q&A
===

**Comment by hueitan** [comment]
Actually is **Achieved**, not _Closed_ 😄
