### ISSUE TITLE
Make it available to be ready in used for gitbook

### ISSUE THREAD

**Issue by hueitan** [hueitan/javascript-sdk-design#4]

**Comment by huei90** [comment]
anyone wants to contribute?

**Comment by suzmas** [comment]
I'm reading through this for fun and noticed areas that could be improved by grammar correction. Are you open to pull requests?

**Comment by hueitan** [comment]
Sure! Improve grammar is definitely welcome and also this is one of the
important step in this repo!

And yes, pr is 100% welcome =)

**Comment by hueitan** [comment]
It is already being used in the gitbook https://huei90.gitbooks.io/javascript-sdk-design/content/, but it can be improved for more sub title content.
