### ISSUE TITLE
Tracking the number of Stars achievement <3

### ISSUE THREAD

**Issue by hueitan** [hueitan/javascript-sdk-design#7]
Version 1.0.0 of `javascript-sdk-design`

_the first milestone - 200 stars achievement 🎉_

**Comment by huei90** [comment]
300 stars achievement in 2017 💥

**Comment by hueitan** [comment]
amazing, it is 400 starts now in Jul 2017 without any advertisement or forum distribution. 💥

**Comment by hueitan** [comment]
<p align="center"><img src="https://user-images.githubusercontent.com/2560096/35181495-ada3322e-fdfd-11e7-9038-f594b2513124.png"/>
</p>
<p align="center"><span>Can you believe this? it is now 500 stars 🌟 </span></p>

**Comment by hueitan** [comment]
700 stars achievement in Aug 2019

**Comment by hueitan** [comment]
<p align="center">800 🌟 now, can we reach 1k?<p>

<p align="center">
<img src="https://user-images.githubusercontent.com/2560096/68253501-5308d100-0028-11ea-8dde-ff066dd79ed9.png"/>
</p>

**Comment by hueitan** [comment]
900 stars achievement in July 2020

**Comment by hueitan** [comment]
Great milestone before the end of 2020!

![image](https://user-images.githubusercontent.com/2560096/99194488-f504e280-277f-11eb-9971-825cf2f73420.png)
